### PR TITLE
Fix add member binding error

### PR DESCRIPTION
**Pull request by petetong1989**

### CODE REVIEW

**Comment by sumanth-lingappa** [comment]
Thank you for your PR @petetong1989 . Please accept the CLA to accept your contributions.
Refer: https://github.com/netscaler/ansible-collection-netscaleradc/blob/main/CONTRIBUTING.md

**Comment by petetong1989** [comment]
Hi @

> Thank you for your PR @petetong1989 . Please accept the CLA to accept your contributions. Refer: https://github.com/netscaler/ansible-collection-netscaleradc/blob/main/CONTRIBUTING.md

Hi @sumanth-lingappa I've accepted the CLA already. However, I noticed I was using my local git user pzhang, not my public git username. Hope this won't cause too much inconvenience.

I have a ticket from Citrix for reference, the support TAC suggested me submit a PR here. #82820148

**Comment by sumanth-lingappa** [comment]
@petetong1989 . Thank you for your reply.
Is it possible to accept your CLA via this github-account, since you have raised the PR with `peteong1089` account?
Sorry for the inconvenience.

**Comment by petetong1989** [comment]
> @petetong1989 . Thank you for your reply. Is it possible to accept your CLA via this github-account, since you have raised the PR with `peteong1089` account? Sorry for the inconvenience.

Hi @sumanth-lingappa I've accepted CLA with the account `petetong1989`, please check the screenshot below
image

**Comment by petetong1989** [comment]
Hey, @sumanth-lingappa I am going to switch the username to push the commit again, as pzhang was my internal username of our company git. This account doesn't have the authority to accept CLA.

**Pull request closed without merging**
